stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: registry.gitlab.com/symmehub/teaching/positron:latest
  script:
    # Source conda env from what found in bashrc
    # - source activate $(head -1 ~/.bashrc | cut -d' ' -f3)
    - jupyter-book clean ./book
    - jupyter-book build ./book
  artifacts:
    paths:
      - ./book/_build/
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci-run/
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  tags:
    - docker
pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv ./book/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci-run/
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  tags:
    - docker
