stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: continuumio/miniconda3:latest
  script:
    - conda env create -f environment.yml
    - source activate jupyter_book
    - jupyter-book clean book
    - jupyter-book build book
  artifacts:
    paths:
      - _build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci-run/
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  tags:
    - docker
